### PR TITLE
Cumulus 1816 behavior

### PR DESCRIPTION
**Pull request by flamingbear**
Only for example behavior.  You might know a much better way to do this.  But this was what hit my head first.

### CODE REVIEW

**Comment by bt6453** [comment]
This is good, but it still fills in the query params if the home page is refreshed. I think I'm going to work off this and see what I can do.

**Comment by flamingbear** [comment]
> This is good, but it still fills in the query params if the home page is refreshed. I think I'm going to work off this and see what I can do.

when refreshed with a F5 full browser refresh or something else?

**Comment by bt6453** [comment]
Yeah with full refresh from the refresh button or cmd+R

**Comment by flamingbear** [comment]
@bt6453 your solution was much better.  Closing this

**Pull request closed without merging**
