### PR TITLE
upgrade node to 12.18.0 to match core

### PR DESCRIPTION
**Pull request by flamingbear**
**Summary:** updates node to match core and updates cypress to latest
**NOTE**: This should be merged when cumulus core merges their upgrade to 12.18.0

## Changes

* node => 12.18.0
* cypress => 4.8.0

## PR Checklist

- [x ] Update CHANGELOG
- [ ] Unit tests
- [ ] Adhoc testing
- [ ] Integration tests

### CODE REVIEW

**Comment by jennyhliu** [comment]
.circleci/config.yml still uses node:10.16.3
babel.config.js uses node: '10.6.3'
Should we update these?

**Comment by flamingbear** [comment]
> .circleci/config.yml still uses node:10.16.3
> babel.config.js uses node: '10.6.3'
> Should we update these?

Yes.  my `rg` command didn't find those. I'll fix it.

**Comment by jennyhliu** [comment]
`cumulus-dashboard/config/webpack.config.test.js` has `node: '10.6.3'`

**Comment by flamingbear** [comment]
> `cumulus-dashboard/config/webpack.config.test.js` has `node: '10.6.3'`

Sorry that also was missed because it wasn't 10.16.3.

**Pull request merged**
