### PR TITLE
[CUMULUS-2549] Collections table sorting

### PR DESCRIPTION
**Pull request by dopeters**
**Summary:** Make stats and MMT link columns sortable on collections overview page

Addresses [CUMULUS-2549: Dashboard: As a Cumulus Operator, I need to be able to sort every column in the Collections Overview table](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2549)

## Changes

* Created sortable table utils file to contain helper function
* Handle custom sorting methods that are passed to the table config - modified some code from react-table. This can't be overridden when manual sorting is set to true, which is necessary for the server side sorting of the other columns. Instead implemented custom versions for our code

## PR Checklist

- [x] Update CHANGELOG
- [ ] Unit tests
- [x] Adhoc testing
- [ ] Integration tests

### CODE REVIEW

**Comment by jjmccoy** [comment]
UI/UX Review: Tested all columns in the Collections table and functionality looks good. 
Overall Review: Really like the simplicity of the sortable table util and custom sorting solutions for this complex issue.

**Comment by jjmccoy** [comment]
@dopeters Update: Reviewed a larger set of records (86) with Matt S. since the local only has 6 records and noticed that the columns that are newly able to sort are not sorting the whole set but just sorting what is on the page. MMT column was what flagged us when it wasn't sorting properly for ascending order: It should have been on the last page but was the last record on page one instead.

**Comment by dopeters** [comment]
> @dopeters Update: Reviewed a larger set of records (86) with Matt S. since the local only has 6 records and noticed that the columns that are newly able to sort are not sorting the whole set but just sorting what is on the page. MMT column was what flagged us when it wasn't sorting properly for ascending order: It should have been on the last page but was the last record on page one instead.

Ah yeah thanks for catching this this. Will fix

**Comment by dopeters** [comment]
Closing for now as the ticket is blocked and it is currently not planned work

**Pull request closed without merging**
