### PR TITLE
CUMULUS-2022: Improve search character limit

### PR DESCRIPTION
**Pull request by jennyhliu**
**Summary:** Summary of changes

Addresses [CUMULUS-2022: Search Module: Character Limit Improvement](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2022)

## Changes

* Improve search character limit
* whitelist node-forge until @cumulus/api @cumulus-cmrjs version updates

## PR Checklist

- [x] Update CHANGELOG
- [ ] Unit tests
- [ ] Adhoc testing
- [ ] Integration tests

### CODE REVIEW

**Comment by jjmccoy** [comment]
Looks good. I would suggest making the default `search input` length based on the max character limit instead of the `on focus` jumping interaction from min to max length since we have plenty of space in the search module row. Also, I noticed that the `"x" button` to clear and `search icon button` are on top of each other now. 

Screen Shot 2020-10-05 at 12 30 45 PM

**Comment by jennyhliu** [comment]
@jjmccoy I made updates to address your comments.  Thanks

**Comment by jjmccoy** [comment]
@jennyhliu Looks great. I would suggest making the search box character length on the "Reconciliation Reports" overview longer and all is good. Thanks.

**Comment by jennyhliu** [comment]
> @jennyhliu Looks great. I would suggest making the search box character length on the "Reconciliation Reports" overview longer and all is good. Thanks.

Ah, I missed that one.  Updated.  Thanks!

**Review by jjmccoy — APPROVED** [review]
LGTG!

**Pull request merged**
