### PR TITLE
CUMULUS-2023:Update filter drop downs to have the same order as columns

### PR DESCRIPTION
**Pull request by jennyhliu**
**Summary:** Summary of changes

Addresses [CUMULUS-2023: Search Module: Filter Ordering](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2023)

## Changes

* Update filter drop downs to have the same order as columns

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Adhoc testing
- [ ] Integration tests

### CODE REVIEW

**Comment by jjmccoy** [comment]
@jennyhliu I have one question regarding 'Executions'. Is the 'Workflow' filter the same as 'Type' in the table? If so, we might want to rename the 'Type' column to 'Workflow' so there is better context for the user.

**Comment by jennyhliu** [comment]
> @jennyhliu I have one question regarding 'Executions'. Is the 'Workflow' filter the same as 'Type' in the table? If so, we might want to rename the 'Type' column to 'Workflow' so there is better context for the user.

Yes.  Renamed.

**Comment by jjmccoy** [comment]
> > @jennyhliu I have one question regarding 'Executions'. Is the 'Workflow' filter the same as 'Type' in the table? If so, we might want to rename the 'Type' column to 'Workflow' so there is better context for the user.
> 
> Yes. Renamed.

Awesome! Thanks for the clarification and update.

**Review by jjmccoy — APPROVED** [review]
LGTG! Thanks -- this will really help with continuity and context.

**Pull request merged**
