### PR TITLE
[CUMULUS-2086] GNF Report Styling

### PR DESCRIPTION
**Pull request by bt6453**
**Summary:** Summary of changes

Addresses [CUMULUS-2086: Reports: GNF View - Overall Style](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2086)

## Changes

* Added the Granule Not Found count, which sums the red dots in the table
* Added a border between the heading and the table

## PR Checklist

- [x] Update CHANGELOG
- [ ] Unit tests
- [X] Adhoc testing
- [x] Integration tests

### CODE REVIEW

**Comment by jjmccoy** [comment]
Looks good, Brian! There are just a few tweaks. The 'Download Report' button has a misspelling. If you can take a quick look at the spacing in `heading__wrapper--border` and the `h2` (Granules Not Found with badge). The spacing is too tight between the date range/status area and the `h2` and too much space between the `h2` and the filters. 

Screen Shot 2020-09-25 at 8 29 44 AM

**Suggestion:**
Since the `h2` is really the beginning of the `page__section` and relates to the table not part of the heading, I would suggest to remove it from the `heading__wrapper--border` and put it in `page__section` in its own `div` (in the example below, I named it `title-count `-- you can name it whatever you want). Then you can add the `border-bottom` and a little `padding `between the `h2` and its `div`. Then in the React component file, remove the `--border` syntax from `heading__wrapper` and that should remove the border from the header section. Then you can add a `margin-top` of `1.5em` to the `h2's div` for a little space between the heading and the page content.

CSS code used for the new `div` for the `h2`:
```
border-bottom: 1px solid $lightest-grey;
padding-bottom: 1em;
margin-top: 1.5em; 
```
Screen Shot 2020-09-25 at 9 06 47 AM

**Comment by bt6453** [comment]
Updated! Thanks for the great suggestions @jjmccoy

**Comment by jjmccoy** [comment]
> Updated! Thanks for the great suggestions @jjmccoy

Awesome work. Looks great! Thanks, @bt6453!

**Comment by jjmccoy** [comment]
You did it! You are a styling pro now.

**Review by jjmccoy — APPROVED** [review]
LGTG!

**Pull request merged**
