### PR TITLE
[CUMULUS-2066] Improve Dashboard Accessibility

### PR DESCRIPTION
**Pull request by dopeters**
**Summary:** Add accessibility plugins and fix the errors they flag

Addresses [CUMULUS-2066: Dashboard: Add Aria-Labels & Alt/Title Tags](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2066)

## Changes

* Added jsx-a11y plugin to eslint - this checks the code itself for various accessibility issues
* Added @axe-core/react - this checks the rendered DOM for accessibility issues
* Fix errors triggered by both plugins - specifically all the ones relating to buttons and form labels
* Various fixes to make buttons and form labels look/work correctly while passing accessibility checks 

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Adhoc testing
- [ ] Integration tests

### CODE REVIEW

**Comment by jjmccoy** [comment]
Great work! I noticed issues with pagination: I can enter the page number I want to go to but the "previous" and "next" buttons aren't working. They are the only buttons that I noticed issues with.

**Comment by jjmccoy** [comment]
Also, the table header with the pagination the form control inputs (pagination number and show per page) do not have a corresponding label and screen readers will not be able to scan this.

**Comment by jjmccoy** [comment]
I'm using Chrome Extensions to test: I had to default to Wave instead of Axe-coconut - Web Accessibility Testing (not working for some reason -- just getting error). I'll try to test with axe tomorrow to see if I missed anything.

**Comment by dopeters** [comment]
@jjmccoy Thanks! I fixed the pagination button (this was actually broken in my previous PR 😓 https://github.com/nasa/cumulus-dashboard/pull/880)

Also, I added labels for page and limit that not visible so that screen readers can pick them up (used the `.sr-only` class)

**Comment by jjmccoy** [comment]
Thank you for the updates!

**Review by jjmccoy — APPROVED** [review]
LGTG! Thank you. This will make our platform more compliant.

**Pull request merged**
