### PR TITLE
Update Reconciliation Component

### PR DESCRIPTION
**Pull request by ifestus**
Make quick reference changes to reconciliation-report.js component to facilitate changes made in the Cumulus API.

### CODE REVIEW

**Comment by ifestus** [comment]
I'm checking whether or not more work needs to go into this. The page that lists reconciliation reports is not affected by the api changes, but the page that allows you to dive into each reconciliation report (clicking on the filename of a report) requires changes.

One thing I need to check, yet, is the `metaAccessors` on line 21 in `scripts/components/reconciliation-reports/reconciliation-report.js` - `okFileCount` no longer exists in the `record.data` object, it exists in two places: `record.data.filesInCumulus.onlyInS3` and `record.data.filesInCumulus.onlyInDynamoDb` objects.

**Comment by jennyhliu** [comment]
image
The left botton corner has `.2`, and almost all the pages have this, not sure why it's there.  The `master` branch doesn't have it.

**Comment by jennyhliu** [comment]
> image
> The left botton corner has `.2`, and almost all the pages have this, not sure why it's there. The `master` branch doesn't have it.

**Comment by ifestus** [comment]
> I realized that the text is `Cumulus API Version: 1.11.2`, and it can't be read from the pages except the home page.

Oh dang, that's an issue. I can create another ticket for that, and let me know if you disagree, but I think it's out of scope for this specific ticket.

**Comment by markdboyd** [comment]
Replaced by #559

**Pull request closed without merging**
