### PR TITLE
CUMULUS-3502:Update localstack to v3 and node to 16.19.0

### PR DESCRIPTION
**Pull request by jennyhliu**
**Summary:** Summary of changes

Addresses [CUMULUS-3502: Upgrade localstack to v3.0.0](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3502)

## Changes

* Detailed list or prose of changes
* ...

### Issues
There is an issue with localstack v3, it returns `AWS stepfunctions.DescribeExecution => 400 (InvalidName)` when execution doesn't exist, instead of `ExecutionDoesNotExist`.

https://github.com/localstack/localstack/blob/v3.0.0/localstack/services/stepfunctions/provider.py#L115

This causes api call to fail.
`GET /executions/status/arn:aws:states:us-east-1:123456789012:execution:TestSourceIntegrationIngestAndPublishGranuleStateMachine-yCAhWOss5Xgo:b313e777-d28a-435b-a0dd-f1fad08116t1 400`

api log:
```
{"error":{"name":"InvalidName","message":"null; Function params: [\n  {\n    \"executionArn\": \"arn:aws:states:us-east-1:123456789012:execution:TestSourceIntegrationIngestAndPublishGranuleStateMachine-yCAhWOss5Xgo:b313e777-d28a-435b-a0dd-f1fad08116t1\"\n  }\n]","stack":["InvalidName: null","    at /Users/jhliu/cumulus-rds/packages/aws-client/utils.js:42:15","    at Object.executionExists (/Users/jhliu/cumulus-rds/packages/aws-client/StepFunctions.js:61:105)","    at get (/Users/jhliu/cumulus-rds/packages/api/endpoints/execution-status.js:147:27)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)"]},"level":"error","message":"null; Function params: [\n  {\n    \"executionArn\": \"arn:aws:states:us-east-1:123456789012:execution:TestSourceIntegrationIngestAndPublishGranuleStateMachine-yCAhWOss5Xgo:b313e777-d28a-435b-a0dd-f1fad08116t1\"\n  }\n]","sender":"@cumulus/api","timestamp":"2023-11-29T00:50:20.993Z"}
[29/Nov/2023:00:50:20 +0000] "GET /executions/status/arn:aws:states:us-east-1:123456789012:execution:TestSourceIntegrationIngestAndPublishGranuleStateMachine-yCAhWOss5Xgo:b313e777-d28a-435b-a0dd-f1fad08116t1 HTTP/1.1"400 471 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0" -
```
The issue is worked around with https://github.com/nasa/cumulus/pull/3523

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Adhoc testing
- [ ] Integration tests

### CODE REVIEW

**Comment by jjmccoy** [comment]
When I run `localstack` I'm getting that it doesn't notice the node change from 14 to 16 even though when I do `nvm use` I get the confirmation that we are 'Now using node v16.19.0 (npm v8.19.3)' but it shows the image below. I see that the docker node versions have been changed in the files but I don't know what is happening here:

Screenshot 2023-12-01 at 1 33 11 PM

**Comment by jjmccoy** [comment]
@jennyhliu Looks good, but M1 Mac still has an issue with `localAPI` (related to `elasticsearch`). No longer getting errors for `localstack`.

**Comment by jjmccoy** [comment]
Need another reviewer who is on Intel Mac to confirm overall.

**Review by Jkovarik — APPROVED** [review]
Looks good to me!

**Pull request merged**
